# Generated by Django 4.0 on 2022-09-19 16:19

import clg_api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', clg_api.models.MyCustomField(null=True)),
                ('updated_at', clg_api.models.MyCustomField(null=True)),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.BinaryField()),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.category')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', clg_api.models.MyCustomField(null=True)),
                ('updated_at', clg_api.models.MyCustomField(null=True)),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('manufactured_date', models.DateField(default=datetime.datetime(2022, 9, 19, 22, 4, 33, 218061), null=True)),
                ('photo', models.BinaryField(null=True)),
                ('description', models.TextField(null=True)),
                ('rating', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.category')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.subcategory')),
                ('vendor_id', models.ForeignKey(db_column='vendor_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=clg_api.models.uuid_generate, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('creaed_at', clg_api.models.MyCustomField(null=True)),
                ('updated_at', clg_api.models.MyCustomField(null=True)),
                ('updated_by', models.CharField(max_length=150)),
                ('is_void', models.BooleanField(default=False)),
                ('void_remarks', models.CharField(max_length=150, null=True)),
                ('note', models.CharField(max_length=1000, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.product')),
                ('vendor_id', models.ForeignKey(db_column='vendor_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='user.user')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district_id', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.district')),
                ('province_id', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.province')),
            ],
            options={
                'db_table': 'municipality',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='province_id',
            field=models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clg_api.province'),
        ),
    ]
