# Generated by Django 4.0 on 2022-09-19 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 22, 4, 49, 159782), null=True),
        ),
    ]
