# Generated by Django 4.0 on 2022-09-22 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0007_order_address_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 17, 13, 20, 929164), null=True),
        ),
    ]
