# Generated by Django 4.0 on 2022-09-22 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0010_order_quantity_alter_product_manufactured_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocard',
            name='customer',
        ),
        migrations.AddField(
            model_name='addtocard',
            name='customer_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='addtocard',
            name='product',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 20, 30, 40, 285490), null=True),
        ),
    ]
