# Generated by Django 4.0 on 2022-09-22 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0011_remove_addtocard_customer_addtocard_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 20, 37, 46, 577925), null=True),
        ),
        migrations.AlterModelTable(
            name='addtocard',
            table='add_to_card',
        ),
    ]
