# Generated by Django 4.0 on 2022-09-26 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0013_rename_product_addtocard_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 14, 40, 27, 933026), null=True),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
