# Generated by Django 4.0 on 2022-09-26 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0014_remove_order_address_remove_order_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 14, 44, 44, 577488), null=True),
        ),
    ]
