# Generated by Django 4.1.3 on 2023-03-21 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0016_remove_product_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 13, 57, 10, 595874), null=True),
        ),
    ]
