# Generated by Django 4.1.3 on 2023-04-22 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0018_alter_product_manufactured_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 22, 20, 4, 39, 920740), null=True),
        ),
    ]
