from clg_api.views.views_product_buy_create import *
from clg_api.views.views_login import *
from clg_api.views.views_forgot_password import *
from clg_api.views.views_product_list import *
from clg_api.views.views_vendor_register import *
from clg_api.views.views_product_create import *
from clg_api.views.views_province_list import *
from clg_api.views.views_district import *
from clg_api.views.views_municipality import *
from clg_api.views.views_vendor_product_list import *
from clg_api.views.views_user_register import *
from clg_api.views.views_vendor_signup import *
from clg_api.views.views_category import *
from .views_order import *
from .views_otp_generate import *
from .views_matplot import *