# Generated by Django 4.0 on 2022-09-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clg_api', '0004_alter_product_manufactured_date'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.ManyToManyField(blank=True, db_column='category_id', related_name='+', to='clg_api.Category'),
        ),
    ]
