# Generated by Django 4.0 on 2022-09-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
