# Generated by Django 4.0 on 2022-09-26 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_order_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='citizenship_back_side',
        ),
        migrations.RemoveField(
            model_name='user',
            name='citizenship_front_side',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
    ]
